version: '3.8'

services:

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: pmt-db
    restart: always
    environment:
      POSTGRES_DB: pmt_db
      POSTGRES_USER: pmt_admin
      POSTGRES_PASSWORD: pmt_admin_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pmt-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pmt_db
      SPRING_DATASOURCE_USERNAME: pmt_admin
      SPRING_DATASOURCE_PASSWORD: pmt_admin_pass
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: pmt-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4000"

volumes:
  postgres_data:
