
spring:
  datasource:
    url: jdbc:postgresql://db:5432/pmt_db
    username: pmt_admin
    password: pmt_admin_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: pmt
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

management:
  endpoints:
    web.exposure.include: health,info
